<a href="https://colab.research.google.com/github/Kitiksha1000/SkyCast/blob/main/Skycast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Import the train and test data

In [ ]:
df=pd.read_csv("/content/train.csv")
df.head()

,Serial Number,Unnamed: 0.1,Unnamed: 0,Company Name,Location,Datum,Detail,Status Rocket,Rocket,Status Mission
0,3677,3676,3676,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Thu Apr 18, 1968 10:30 UTC",Voskhod | Cosmos 214,StatusRetired,NaN,1
1,64,63,63,CASC,"LC-101, Wenchang Satellite Launch Center, China","Fri Dec 27, 2019 12:45 UTC",Long March 5 | Shijian-20,StatusActive,NaN,1
2,3930,3929,3929,RVSN USSR,"Site 86/1, Kapustin Yar, Russia","Thu Nov 04, 1965 05:31 UTC",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,NaN,1
3,2035,2034,2034,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Sat Nov 15, 1986 21:35 UTC",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,NaN,1
4,1310,1309,1309,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia","Mon Jun 15, 1998 22:58 UTC",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,NaN,0

In [ ]:
df_test=pd.read_csv("/content/test.csv")
df_test.shape

(865, 9)

# Data Exploration

In [ ]:
df.shape

(3459, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3459 entries, 0 to 3458
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Serial Number   3459 non-null   int64
 1   Unnamed: 0.1    3459 non-null   int64
 2   Unnamed: 0      3459 non-null   int64
 3   Company Name    3459 non-null   object
 4   Location        3459 non-null   object
 5   Datum           3459 non-null   object
 6   Detail          3459 non-null   object
 7   Status Rocket   3459 non-null   object
 8    Rocket         751 non-null    object
 9   Status Mission  3459 non-null   int64
dtypes: int64(4), object(6)
memory usage: 270.4+ KB

**1. Checking for missing values**

In [ ]:
df.isnull().sum()

Serial Number        0
Unnamed: 0.1         0
Unnamed: 0           0
Company Name         0
Location             0
Datum                0
Detail               0
Status Rocket        0
 Rocket           2708
Status Mission       0
dtype: int64

**2. Dropping repeated columns**

In [ ]:
(df['Unnamed: 0.1']==df['Unnamed: 0']).all()

np.True_

In [ ]:
df1=df.drop(columns=['Unnamed: 0','Unnamed: 0.1'])
df1.head()
df1.shape

(3459, 8)

In [ ]:
#Test
df1_test=df_test.drop(columns=['Unnamed: 0','Unnamed: 0.1'])
df1_test.shape

(865, 7)

In [ ]:
df1.head()

,Serial Number,Company Name,Location,Datum,Detail,Status Rocket,Rocket,Status Mission
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Thu Apr 18, 1968 10:30 UTC",Voskhod | Cosmos 214,StatusRetired,NaN,1
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China","Fri Dec 27, 2019 12:45 UTC",Long March 5 | Shijian-20,StatusActive,NaN,1
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia","Thu Nov 04, 1965 05:31 UTC",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,NaN,1
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Sat Nov 15, 1986 21:35 UTC",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,NaN,1
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia","Mon Jun 15, 1998 22:58 UTC",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,NaN,0

**3. Exploring each column one by one**

In [ ]:
df1.columns = df1.columns.str.strip()
rocket_counts = df1['Rocket'].value_counts()
print(rocket_counts)

Rocket
450.0       117
200.0        59
40.0         41
30.8         31
62.0         30
41.8         28
109.0        27
64.68        26
29.75        25
90.0         25
48.5         22
50.0         22
31.0         17
59.0         16
29.15        16
29.0         15
21.0         14
35.0         14
37.0         12
56.5         12
164.0        12
153.0        11
69.7         11
350.0        10
7.5          10
47.0         10
65.0         10
1,160.0       9
5.3           7
25.0          7
85.0          7
123.0         7
45.0          7
112.5         6
120.0         6
80.0          5
145.0         5
59.5          4
115.0         4
63.23         4
46.0          3
136.6         3
7.0           3
190.0         3
133.0         3
135.0         2
39.0          2
140.0         2
5,000.0       2
130.0         2
15.0          1
55.0          1
12.0          1
20.14         1
28.3          1
Name: count, dtype: int64

In [ ]:
df2=df1.drop(columns=['Rocket'])
df2.head()

,Serial Number,Company Name,Location,Datum,Detail,Status Rocket,Status Mission
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Thu Apr 18, 1968 10:30 UTC",Voskhod | Cosmos 214,StatusRetired,1
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China","Fri Dec 27, 2019 12:45 UTC",Long March 5 | Shijian-20,StatusActive,1
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia","Thu Nov 04, 1965 05:31 UTC",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,1
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Sat Nov 15, 1986 21:35 UTC",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,1
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia","Mon Jun 15, 1998 22:58 UTC",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,0

In [ ]:
#Test
df1_test.columns = df1_test.columns.str.strip()
df2_test=df1_test.drop(columns=['Rocket'])
df2_test.head()

,Serial Number,Company Name,Location,Datum,Detail,Status Rocket
0,2122,NASA,"LC-39A, Kennedy Space Center, Florida, USA","Thu Jul 25, 1985 21:00 UTC",Space Shuttle Challenger | STS-51-F,StatusRetired
1,18,SpaceX,"SLC-40, Cape Canaveral AFS, Florida, USA","Tue Jun 30, 2020 20:10 UTC",Falcon 9 Block 5 | GPS III SV03,StatusActive
2,3716,RVSN USSR,"Site 133/3, Plesetsk Cosmodrome, Russia","Tue Nov 21, 1967 14:29 UTC",Cosmos-2I (63SM) | Cosmos 191,StatusRetired
3,585,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Mon Nov 18, 2013 18:28 UTC",Atlas V 401 | MAVEN,StatusActive
4,4249,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Mon Oct 10, 1960 14:27 UTC",Molniya | 1M n†­1 (Marsnik 1),StatusRetired

In [ ]:
df2.shape

(3459, 7)

In [ ]:
df2_test.shape

(865, 6)

In [ ]:
df2['Status Rocket'].value_counts()

Status Rocket
StatusRetired    2844
StatusActive      615
Name: count, dtype: int64

In [ ]:
df2['Company Name'].value_counts()

Company Name
RVSN USSR           1433
Arianespace          223
General Dynamics     211
CASC                 186
NASA                 166
VKS RF               152
US Air Force         128
ULA                  114
Boeing               111
Martin Marietta       91
SpaceX                71
MHI                   69
Lockheed              66
Northrop              63
ISRO                  61
Roscosmos             46
ILS                   35
Sea Launch            30
ISAS                  24
Kosmotras             15
US Navy               14
Eurockot              12
ISA                   12
ESA                   12
Blue Origin           11
Rocket Lab             9
ExPace                 8
CNES                   7
Land Launch            7
IAI                    7
JAXA                   6
AMBA                   6
MITT                   6
ASI                    6
CASIC                  4
Arm??e de l'Air        4
KCST                   4
UT                     4
Exos                   3
CECLES                 3
SRC                    3
AEB                    2
KARI                   2
OKB-586                2
RAE                    2
Yuzhmash               2
Sandia                 1
Starsem                1
Virgin Orbit           1
Khrunichev             1
IRGC                   1
Landspace              1
Name: count, dtype: int64

**4. Combining entries in column `'Company Name'` with frequency less than 10 as 'Other'**

In [ ]:
threshold = 10
value_counts = df2['Company Name'].value_counts()
df2['Company Name'] = df2['Company Name'].apply(
    lambda x: x if value_counts[x] > threshold else 'Other'
)

In [ ]:
df2['Company Name'].value_counts().shape

(26,)

In [ ]:
df2['Company Name'].unique()

array(['RVSN USSR', 'CASC', 'VKS RF', 'NASA', 'Arianespace', 'Lockheed',
       'Sea Launch', 'General Dynamics', 'ISRO', 'Kosmotras', 'Boeing',
       'Other', 'Martin Marietta', 'SpaceX', 'ILS', 'MHI', 'Roscosmos',
       'ISA', 'ESA', 'Blue Origin', 'ULA', 'US Air Force', 'Northrop',
       'US Navy', 'ISAS', 'Eurockot'], dtype=object)

In [ ]:
#Test
company_list = ['RVSN USSR', 'CASC', 'VKS RF', 'NASA', 'Arianespace', 'Lockheed',
       'Sea Launch', 'General Dynamics', 'ISRO', 'Kosmotras', 'Boeing',
        'Martin Marietta', 'SpaceX', 'ILS', 'MHI', 'Roscosmos',
       'ISA', 'ESA', 'Blue Origin', 'ULA', 'US Air Force', 'Northrop',
       'US Navy', 'ISAS', 'Eurockot']

df2_test['Company Name'] = df2_test['Company Name'].apply(lambda x: x if x in company_list else 'Other')

In [ ]:
df2_test['Company Name'].value_counts().shape

(26,)

In [ ]:
df2['Datum'].unique()

array(['Thu Apr 18, 1968 10:30 UTC', 'Fri Dec 27, 2019 12:45 UTC',
       'Thu Nov 04, 1965 05:31 UTC', ..., 'Sat Nov 03, 1973 05:45 UTC',
       'Wed May 17, 1967 16:05 UTC', 'Thu Jul 05, 2007 20:08 UTC'],
      dtype=object)

**5. Extracting year, month and time of launch as separate columns**

In [ ]:
import pandas as pd

def extract_date_time(date_string):
  try:

    parts = date_string.split(',')[0].split(' ')[1:] + date_string.split(',')[1].strip().split(' ')[:2]

    date_time_string = ' '.join(parts)

    return date_time_string
  except IndexError:

    return None

df2['Extracted_Date_Time'] = df2['Datum'].apply(extract_date_time)
df2['Extracted_Date'] = df2['Extracted_Date_Time'].str.split(' ').str[0:2].str.join(' ')
df2['Extracted_Year'] = df2['Extracted_Date_Time'].str.split(' ').str[2]

df2.head()

,Serial Number,Company Name,Location,Datum,Detail,Status Rocket,Status Mission,Extracted_Date_Time,Extracted_Date,Extracted_Year
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Thu Apr 18, 1968 10:30 UTC",Voskhod | Cosmos 214,StatusRetired,1,Apr 18 1968 10:30,Apr 18,1968
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China","Fri Dec 27, 2019 12:45 UTC",Long March 5 | Shijian-20,StatusActive,1,Dec 27 2019 12:45,Dec 27,2019
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia","Thu Nov 04, 1965 05:31 UTC",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,1,Nov 04 1965 05:31,Nov 04,1965
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Sat Nov 15, 1986 21:35 UTC",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,1,Nov 15 1986 21:35,Nov 15,1986
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia","Mon Jun 15, 1998 22:58 UTC",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,0,Jun 15 1998 22:58,Jun 15,1998

In [ ]:
#Test
df2_test['Extracted_Date_Time'] = df2_test['Datum'].apply(extract_date_time)
df2_test['Extracted_Date'] = df2_test['Extracted_Date_Time'].str.split(' ').str[0:2].str.join(' ')
df2_test['Extracted_Year'] = df2_test['Extracted_Date_Time'].str.split(' ').str[2]

In [ ]:

month_mapping = {
    'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
    'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12
}

df2['Extracted_Month'] = df2['Extracted_Date_Time'].str.split(' ').str[0].map(month_mapping)
df2.head()

,Serial Number,Company Name,Location,Datum,Detail,Status Rocket,Status Mission,Extracted_Date_Time,Extracted_Date,Extracted_Year,Extracted_Month
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Thu Apr 18, 1968 10:30 UTC",Voskhod | Cosmos 214,StatusRetired,1,Apr 18 1968 10:30,Apr 18,1968,4
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China","Fri Dec 27, 2019 12:45 UTC",Long March 5 | Shijian-20,StatusActive,1,Dec 27 2019 12:45,Dec 27,2019,12
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia","Thu Nov 04, 1965 05:31 UTC",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,1,Nov 04 1965 05:31,Nov 04,1965,11
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Sat Nov 15, 1986 21:35 UTC",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,1,Nov 15 1986 21:35,Nov 15,1986,11
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia","Mon Jun 15, 1998 22:58 UTC",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,0,Jun 15 1998 22:58,Jun 15,1998,6

In [ ]:
#Test
df2_test['Extracted_Month'] = df2_test['Extracted_Date_Time'].str.split(' ').str[0].map(month_mapping)

In [ ]:
def extract_time_as_float(time_str):

    try:

        parts = time_str.split()
        time_part = parts[-1]
        hour, minute = map(int, time_part.split(':'))
        time_float =np.round(hour + (minute / 60),2)

        return time_float
    except (IndexError, ValueError):

        return None


time_str = "May 17 1967 16:05"
result = extract_time_as_float(time_str)
print(result)

16.08

In [ ]:
df2['Extracted_Time']=df2['Extracted_Date_Time'].apply(extract_time_as_float)
df2.head()

,Serial Number,Company Name,Location,Datum,Detail,Status Rocket,Status Mission,Extracted_Date_Time,Extracted_Date,Extracted_Year,Extracted_Month,Extracted_Time
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Thu Apr 18, 1968 10:30 UTC",Voskhod | Cosmos 214,StatusRetired,1,Apr 18 1968 10:30,Apr 18,1968,4,10.50
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China","Fri Dec 27, 2019 12:45 UTC",Long March 5 | Shijian-20,StatusActive,1,Dec 27 2019 12:45,Dec 27,2019,12,12.75
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia","Thu Nov 04, 1965 05:31 UTC",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,1,Nov 04 1965 05:31,Nov 04,1965,11,5.52
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia","Sat Nov 15, 1986 21:35 UTC",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,1,Nov 15 1986 21:35,Nov 15,1986,11,21.58
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia","Mon Jun 15, 1998 22:58 UTC",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,0,Jun 15 1998 22:58,Jun 15,1998,6,22.97

In [ ]:
#Test
df2_test['Extracted_Time']=df2_test['Extracted_Date_Time'].apply(extract_time_as_float)

In [ ]:
df2.shape

(3459, 12)

**6. Dropping the unncesary columns**

In [ ]:
df2=df2.drop(columns=['Datum','Extracted_Date_Time','Extracted_Date'])
df2.head()

,Serial Number,Company Name,Location,Detail,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Extracted_Time
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",Voskhod | Cosmos 214,StatusRetired,1,1968,4,10.50
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China",Long March 5 | Shijian-20,StatusActive,1,2019,12,12.75
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,1,1965,11,5.52
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,1,1986,11,21.58
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,0,1998,6,22.97

In [ ]:
#Test
df2_test=df2_test.drop(columns=['Datum','Extracted_Date_Time','Extracted_Date'])
df2_test.head()

,Serial Number,Company Name,Location,Detail,Status Rocket,Extracted_Year,Extracted_Month,Extracted_Time
0,2122,NASA,"LC-39A, Kennedy Space Center, Florida, USA",Space Shuttle Challenger | STS-51-F,StatusRetired,1985,7,21.00
1,18,SpaceX,"SLC-40, Cape Canaveral AFS, Florida, USA",Falcon 9 Block 5 | GPS III SV03,StatusActive,2020,6,20.17
2,3716,RVSN USSR,"Site 133/3, Plesetsk Cosmodrome, Russia",Cosmos-2I (63SM) | Cosmos 191,StatusRetired,1967,11,14.48
3,585,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",Atlas V 401 | MAVEN,StatusActive,2013,11,18.47
4,4249,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",Molniya | 1M n†­1 (Marsnik 1),StatusRetired,1960,10,14.45

In [ ]:
df3=df2.copy()
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3459 entries, 0 to 3458
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Serial Number    3459 non-null   int64
 1   Company Name     3459 non-null   object
 2   Location         3459 non-null   object
 3   Detail           3459 non-null   object
 4   Status Rocket    3459 non-null   object
 5   Status Mission   3459 non-null   int64
 6   Extracted_Year   3459 non-null   object
 7   Extracted_Month  3459 non-null   int64
 8   Extracted_Time   3362 non-null   float64
dtypes: float64(1), int64(3), object(5)
memory usage: 243.3+ KB

In [ ]:
#Test
df3_test=df2_test.copy()
df3_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 865 entries, 0 to 864
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Serial Number    865 non-null    int64
 1   Company Name     865 non-null    object
 2   Location         865 non-null    object
 3   Detail           865 non-null    object
 4   Status Rocket    865 non-null    object
 5   Extracted_Year   865 non-null    object
 6   Extracted_Month  865 non-null    int64
 7   Extracted_Time   836 non-null    float64
dtypes: float64(1), int64(2), object(5)
memory usage: 54.2+ KB

In [ ]:
df3['Detail'].value_counts()

Detail
Cosmos-3MRB (65MRB) | BOR-5 Shuttle              5
Proton K/Block D | Zond                          4
Lambda-IV S | Osumi                              4
Titan IV(402)B | DSP                             4
Cosmos-3MRB (65MRB) | BOR-2 Shuttle              3
                                                ..
Space Shuttle Discovery | STS-51-I               1
Atlas IIA | Inmarsat 3-F1                        1
Zenit-3 SLB | AMOS 4                             1
Ariane 5 ECA | Astra 1N, BSAT-3C (JCSAT-110R)    1
Tsyklon-2A | Cosmos 252                          1
Name: count, Length: 3424, dtype: int64

**7. Separating mission and rocket type from `'Detail'` column**

In [ ]:
def separate_rocket_mission(detail_str):

    rocket_type, mission = detail_str.split(" | ")

    return rocket_type, mission


detail_str = "Voskhod | Cosmos 214"
rocket_type, mission = separate_rocket_mission(detail_str)

print(f"Rocket Type: {rocket_type}")
print(f"Mission: {mission}")

Rocket Type: Voskhod
Mission: Cosmos 214

In [ ]:
df3['Rocket_type']=df3['Detail'].apply(lambda x: separate_rocket_mission(x)[0])
df3['Mission']=df3['Detail'].apply(lambda x: separate_rocket_mission(x)[1])
df3.head()

,Serial Number,Company Name,Location,Detail,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Extracted_Time,Rocket_type,Mission
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",Voskhod | Cosmos 214,StatusRetired,1,1968,4,10.50,Voskhod,Cosmos 214
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China",Long March 5 | Shijian-20,StatusActive,1,2019,12,12.75,Long March 5,Shijian-20
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,1,1965,11,5.52,Cosmos-2I (63SM),Cosmos 95
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,1,1986,11,21.58,Molniya-M /Block ML,Molniya-1 n†­127
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,0,1998,6,22.97,Tsyklon-3,Cosmos 2352 to 2357

In [ ]:
#Test
df3_test['Rocket_type']=df3_test['Detail'].apply(lambda x: separate_rocket_mission(x)[0])
df3_test['Mission']=df3_test['Detail'].apply(lambda x: separate_rocket_mission(x)[1])

In [ ]:
df3['Mission'].value_counts()

Mission
DSP                               7
BOR-5 Shuttle                     5
Demo Flight                       5
KH-11                             4
Osumi                             4
                                 ..
Inmarsat 3-F1                     1
AMOS 4                            1
Astra 1N, BSAT-3C (JCSAT-110R)    1
Starlink V1 L5                    1
Cosmos 1059                       1
Name: count, Length: 3407, dtype: int64

Mission has many uniques values and doesnt seem to be useful. However, 'Rocket_type' seems useful column

In [ ]:
df3['Rocket_type'].value_counts()

Rocket_type
Cosmos-3M (11K65M)     360
Voskhod                247
Molniya-M /Block ML    104
Cosmos-2I (63SM)       102
Tsyklon-3               97
                      ...
ZhuQue-1                 1
Scout X-3M               1
Zenit-2 FG               1
Long March 2C/SMA        1
Unha-2                   1
Name: count, Length: 333, dtype: int64

**8. Combining the categories in `'Rocket_type'` column with frequencies less than 40 into 'Other' category.**

In [ ]:
rocket_type_counts = df3['Rocket_type'].value_counts()

threshold = 40

df3['Rocket_type_Grouped'] = df3['Rocket_type'].apply(lambda x: x if rocket_type_counts[x] >= threshold else 'Other')

df3['Rocket_type_Grouped'].value_counts()

Rocket_type_Grouped
Other                   2115
Cosmos-3M (11K65M)       360
Voskhod                  247
Molniya-M /Block ML      104
Cosmos-2I (63SM)         102
Tsyklon-3                 97
Soyuz U                   94
Tsyklon-2                 82
Vostok-2M                 79
Molniya-M /Block 2BL      71
Ariane 5 ECA              59
Delta II 7925             49
Name: count, dtype: int64

In [ ]:
#Test
rocket_type_list = ['Voskhod', 'Cosmos-2I (63SM)', 'Molniya-M /Block ML',
                    'Tsyklon-3', 'Soyuz U', 'Cosmos-3M (11K65M)', 'Tsyklon-2',
                    'Vostok-2M', 'Delta II 7925', 'Ariane 5 ECA', 'Molniya-M /Block 2BL']
df3_test['Rocket_type_Grouped'] = df3_test['Rocket_type'].apply(lambda x: x if x in rocket_type_list else 'Other')

In [ ]:
df3_test['Rocket_type_Grouped'].value_counts()

Rocket_type_Grouped
Other                   540
Cosmos-3M (11K65M)       86
Voskhod                  52
Soyuz U                  31
Tsyklon-3                25
Cosmos-2I (63SM)         24
Tsyklon-2                24
Molniya-M /Block ML      24
Molniya-M /Block 2BL     16
Ariane 5 ECA             16
Vostok-2M                14
Delta II 7925            13
Name: count, dtype: int64

In [ ]:
df3['Rocket_type_Grouped'].unique()

array(['Voskhod', 'Other', 'Cosmos-2I (63SM)', 'Molniya-M /Block ML',
       'Tsyklon-3', 'Soyuz U', 'Cosmos-3M (11K65M)', 'Tsyklon-2',
       'Vostok-2M', 'Delta II 7925', 'Ariane 5 ECA',
       'Molniya-M /Block 2BL'], dtype=object)

In [ ]:
df3.head()

,Serial Number,Company Name,Location,Detail,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Extracted_Time,Rocket_type,Mission,Rocket_type_Grouped
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",Voskhod | Cosmos 214,StatusRetired,1,1968,4,10.50,Voskhod,Cosmos 214,Voskhod
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China",Long March 5 | Shijian-20,StatusActive,1,2019,12,12.75,Long March 5,Shijian-20,Other
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,1,1965,11,5.52,Cosmos-2I (63SM),Cosmos 95,Cosmos-2I (63SM)
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,1,1986,11,21.58,Molniya-M /Block ML,Molniya-1 n†­127,Molniya-M /Block ML
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,0,1998,6,22.97,Tsyklon-3,Cosmos 2352 to 2357,Tsyklon-3

**9.
Dropping `Mission `, `Detail` and `Rocket_type` columns**

In [ ]:
df3=df3.drop(columns=['Mission','Rocket_type'])
df3.head()

,Serial Number,Company Name,Location,Detail,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Extracted_Time,Rocket_type_Grouped
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",Voskhod | Cosmos 214,StatusRetired,1,1968,4,10.50,Voskhod
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China",Long March 5 | Shijian-20,StatusActive,1,2019,12,12.75,Other
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia",Cosmos-2I (63SM) | Cosmos 95,StatusRetired,1,1965,11,5.52,Cosmos-2I (63SM)
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",Molniya-M /Block ML | Molniya-1 n†­127,StatusRetired,1,1986,11,21.58,Molniya-M /Block ML
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia",Tsyklon-3 | Cosmos 2352 to 2357,StatusRetired,0,1998,6,22.97,Tsyklon-3

In [ ]:
df3=df3.drop(columns=['Detail'])
df3.head()

,Serial Number,Company Name,Location,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Extracted_Time,Rocket_type_Grouped
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",StatusRetired,1,1968,4,10.50,Voskhod
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China",StatusActive,1,2019,12,12.75,Other
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia",StatusRetired,1,1965,11,5.52,Cosmos-2I (63SM)
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",StatusRetired,1,1986,11,21.58,Molniya-M /Block ML
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia",StatusRetired,0,1998,6,22.97,Tsyklon-3

In [ ]:
#Test
df3_test=df3_test.drop(columns=['Mission','Rocket_type','Detail'])
df3_test.head()

,Serial Number,Company Name,Location,Status Rocket,Extracted_Year,Extracted_Month,Extracted_Time,Rocket_type_Grouped
0,2122,NASA,"LC-39A, Kennedy Space Center, Florida, USA",StatusRetired,1985,7,21.00,Other
1,18,SpaceX,"SLC-40, Cape Canaveral AFS, Florida, USA",StatusActive,2020,6,20.17,Other
2,3716,RVSN USSR,"Site 133/3, Plesetsk Cosmodrome, Russia",StatusRetired,1967,11,14.48,Cosmos-2I (63SM)
3,585,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",StatusActive,2013,11,18.47,Other
4,4249,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",StatusRetired,1960,10,14.45,Other

In [ ]:
df3.Location.value_counts()

Location
Site 31/6, Baikonur Cosmodrome, Kazakhstan               192
Site 43/4, Plesetsk Cosmodrome, Russia                   173
Site 132/1, Plesetsk Cosmodrome, Russia                  173
Site 41/1, Plesetsk Cosmodrome, Russia                   163
Site 1/5, Baikonur Cosmodrome, Kazakhstan                152
                                                        ...
Tai Rui Barge, Yellow Sea                                  1
K-496 Submarine, Barents Sea Launch Area, Barents Sea      1
Launch Plateform, Shahrud Missile Test Site                1
K-84 Submarine, Barents Sea Launch Area, Barents Sea       1
NB-52B Carrier, Cape Canaveral AFS, Florida, USA           1
Name: count, Length: 134, dtype: int64

**10. Extracting country from `Location ` column**

In [ ]:
def extract_country(location):

    parts = [part.strip() for part in location.split(',')]

    country = parts[-1]

    return country

location = "Site 31/6, Baikonur Cosmodrome, Kazakhstan"
country = extract_country(location)
print(country)

Kazakhstan

In [ ]:
df3['Country']=df3['Location'].apply(extract_country)
df3.head()

,Serial Number,Company Name,Location,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Extracted_Time,Rocket_type_Grouped,Country
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",StatusRetired,1,1968,4,10.50,Voskhod,Russia
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China",StatusActive,1,2019,12,12.75,Other,China
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia",StatusRetired,1,1965,11,5.52,Cosmos-2I (63SM),Russia
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",StatusRetired,1,1986,11,21.58,Molniya-M /Block ML,Russia
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia",StatusRetired,0,1998,6,22.97,Tsyklon-3,Russia

In [ ]:
#Test
df3_test['Country']=df3_test['Location'].apply(extract_country)
df3_test.head()

,Serial Number,Company Name,Location,Status Rocket,Extracted_Year,Extracted_Month,Extracted_Time,Rocket_type_Grouped,Country
0,2122,NASA,"LC-39A, Kennedy Space Center, Florida, USA",StatusRetired,1985,7,21.00,Other,USA
1,18,SpaceX,"SLC-40, Cape Canaveral AFS, Florida, USA",StatusActive,2020,6,20.17,Other,USA
2,3716,RVSN USSR,"Site 133/3, Plesetsk Cosmodrome, Russia",StatusRetired,1967,11,14.48,Cosmos-2I (63SM),Russia
3,585,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",StatusActive,2013,11,18.47,Other,USA
4,4249,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan",StatusRetired,1960,10,14.45,Other,Kazakhstan

In [ ]:
df3['Country'].value_counts()

Country
Russia                            1132
USA                               1085
Kazakhstan                         550
France                             245
China                              198
Japan                              103
India                               61
Pacific Ocean                       30
Iran                                12
New Zealand                          9
Israel                               7
Kenya                                6
Australia                            4
North Korea                          4
New Mexico                           3
Barents Sea                          3
Brazil                               2
South Korea                          2
Pacific Missile Range Facility       1
Yellow Sea                           1
Shahrud Missile Test Site            1
Name: count, dtype: int64

**11. Group countries with frequency less than 60 as 'Others'**

In [ ]:
country_counts = df3['Country'].value_counts()


df3['Country'] = df3['Country'].apply(lambda x: x if country_counts[x] >= 60 else 'Others')

In [ ]:
df3['Country'].value_counts()

Country
Russia        1132
USA           1085
Kazakhstan     550
France         245
China          198
Japan          103
Others          85
India           61
Name: count, dtype: int64

In [ ]:
df3['Country'].unique()

array(['Russia', 'China', 'Kazakhstan', 'USA', 'France', 'Others',
       'India', 'Japan'], dtype=object)

In [ ]:
df3.head()

,Serial Number,Company Name,Location,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Extracted_Time,Rocket_type_Grouped,Country
0,3677,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",StatusRetired,1,1968,4,10.50,Voskhod,Russia
1,64,CASC,"LC-101, Wenchang Satellite Launch Center, China",StatusActive,1,2019,12,12.75,Other,China
2,3930,RVSN USSR,"Site 86/1, Kapustin Yar, Russia",StatusRetired,1,1965,11,5.52,Cosmos-2I (63SM),Russia
3,2035,RVSN USSR,"Site 41/1, Plesetsk Cosmodrome, Russia",StatusRetired,1,1986,11,21.58,Molniya-M /Block ML,Russia
4,1310,VKS RF,"Site 32/1, Plesetsk Cosmodrome, Russia",StatusRetired,0,1998,6,22.97,Tsyklon-3,Russia

In [ ]:
#Test
country_list = ['Russia', 'China', 'Kazakhstan', 'USA', 'France',
                'India', 'Japan']

df3_test['Country'] = df3_test['Country'].apply(lambda x: x if x in country_list else 'Other')

In [ ]:
df3=df3.drop(columns=['Location'])

In [ ]:
#Test
df3_test=df3_test.drop(columns=['Location'])

In [ ]:
df3.head()

,Serial Number,Company Name,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Extracted_Time,Rocket_type_Grouped,Country
0,3677,RVSN USSR,StatusRetired,1,1968,4,10.50,Voskhod,Russia
1,64,CASC,StatusActive,1,2019,12,12.75,Other,China
2,3930,RVSN USSR,StatusRetired,1,1965,11,5.52,Cosmos-2I (63SM),Russia
3,2035,RVSN USSR,StatusRetired,1,1986,11,21.58,Molniya-M /Block ML,Russia
4,1310,VKS RF,StatusRetired,0,1998,6,22.97,Tsyklon-3,Russia

**12. Dropping `'Serial Number `' and `'Extracted_Time'`**

In [ ]:
df4=df3.drop(columns=['Serial Number','Extracted_Time'])
df4.head()

,Company Name,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Rocket_type_Grouped,Country
0,RVSN USSR,StatusRetired,1,1968,4,Voskhod,Russia
1,CASC,StatusActive,1,2019,12,Other,China
2,RVSN USSR,StatusRetired,1,1965,11,Cosmos-2I (63SM),Russia
3,RVSN USSR,StatusRetired,1,1986,11,Molniya-M /Block ML,Russia
4,VKS RF,StatusRetired,0,1998,6,Tsyklon-3,Russia

In [ ]:
df4_serial_number=df3['Serial Number']
df4_serial_number.head()

0    3677
1      64
2    3930
3    2035
4    1310
Name: Serial Number, dtype: int64

In [ ]:
#Test
df4_test=df3_test.drop(columns=['Serial Number','Extracted_Time'])
df4_test.head()

,Company Name,Status Rocket,Extracted_Year,Extracted_Month,Rocket_type_Grouped,Country
0,NASA,StatusRetired,1985,7,Other,USA
1,SpaceX,StatusActive,2020,6,Other,USA
2,RVSN USSR,StatusRetired,1967,11,Cosmos-2I (63SM),Russia
3,ULA,StatusActive,2013,11,Other,USA
4,RVSN USSR,StatusRetired,1960,10,Other,Kazakhstan

In [ ]:
#Test
df4_serial_number_test=df3_test['Serial Number']
df4_serial_number_test.head()

0    2122
1      18
2    3716
3     585
4    4249
Name: Serial Number, dtype: int64

**13. Encoding `Status Rocket` as binary values**

In [ ]:
def encode_status_rocket(df):

    df['Status Rocket'] = df['Status Rocket'].apply(lambda x: 1 if x == 'StatusActive' else 0)
    return df
df4=encode_status_rocket(df4)
df4.head()

,Company Name,Status Rocket,Status Mission,Extracted_Year,Extracted_Month,Rocket_type_Grouped,Country
0,RVSN USSR,0,1,1968,4,Voskhod,Russia
1,CASC,1,1,2019,12,Other,China
2,RVSN USSR,0,1,1965,11,Cosmos-2I (63SM),Russia
3,RVSN USSR,0,1,1986,11,Molniya-M /Block ML,Russia
4,VKS RF,0,0,1998,6,Tsyklon-3,Russia

**14. Dropping target column from train set**

In [ ]:
df4_target=df4['Status Mission']
df4=df4.drop(columns=['Status Mission'])
df4.head()

,Company Name,Status Rocket,Extracted_Year,Extracted_Month,Rocket_type_Grouped,Country
0,RVSN USSR,0,1968,4,Voskhod,Russia
1,CASC,1,2019,12,Other,China
2,RVSN USSR,0,1965,11,Cosmos-2I (63SM),Russia
3,RVSN USSR,0,1986,11,Molniya-M /Block ML,Russia
4,VKS RF,0,1998,6,Tsyklon-3,Russia

In [ ]:
df4['Country'].unique()

array(['Russia', 'China', 'Kazakhstan', 'USA', 'France', 'Others',
       'India', 'Japan'], dtype=object)

In [ ]:
#Test
df4_test=encode_status_rocket(df4_test)
df4_test.head()

,Company Name,Status Rocket,Extracted_Year,Extracted_Month,Rocket_type_Grouped,Country
0,NASA,0,1985,7,Other,USA
1,SpaceX,1,2020,6,Other,USA
2,RVSN USSR,0,1967,11,Cosmos-2I (63SM),Russia
3,ULA,1,2013,11,Other,USA
4,RVSN USSR,0,1960,10,Other,Kazakhstan

**15. Combining it all into a pipeline**

In [ ]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler,MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [ ]:

categorical_columns = ['Company Name', 'Rocket_type_Grouped','Country']
numerical_columns = [ 'Extracted_Year', 'Extracted_Month']

all_categories = {
    col: list(set(df4[col].unique()).union(set(df4_test[col].unique())))
    for col in categorical_columns
}


column_transformer = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(sparse_output=False, categories=[all_categories[col] for col in categorical_columns]), categorical_columns),  # Set explicit categories
        ('num', MinMaxScaler(), numerical_columns)
    ],
    remainder='passthrough'
)

pipeline = Pipeline(steps=[
    ('preprocessor', column_transformer)
])

In [ ]:
train_transformed = pipeline.fit_transform(df4)

In [ ]:
#Test
test_transformed = pipeline.transform(df4_test)

In [ ]:
one_hot_columns = pipeline.named_steps['preprocessor'].transformers_[0][1].get_feature_names_out(categorical_columns)

final_column_names = list(one_hot_columns) + numerical_columns + ['Status Rocket']

train_transformed_df = pd.DataFrame(train_transformed, columns=final_column_names)

In [ ]:
train_transformed_df.shape

(3459, 50)

In [ ]:
df4_target.shape

(3459,)

In [ ]:
#Test
test_transformed_df = pd.DataFrame(test_transformed, columns=final_column_names)
test_transformed_df=test_transformed_df.dropna()

In [ ]:
test_transformed_df.shape

(865, 50)

In [ ]:
train_transformed_df.head()

,Company Name_Other,Company Name_ISRO,Company Name_Kosmotras,Company Name_Lockheed,Company Name_General Dynamics,Company Name_Roscosmos,Company Name_CASC,Company Name_ULA,Company Name_SpaceX,Company Name_MHI,...,Country_Russia,Country_India,Country_China,Country_France,Country_USA,Country_Kazakhstan,Country_Japan,Extracted_Year,Extracted_Month,Status Rocket
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.174603,0.272727,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.984127,1.000000,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.126984,0.909091,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.460317,0.909091,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.650794,0.454545,0.0

In [ ]:
train_transformed_df.columns

Index(['Company Name_Other', 'Company Name_ISRO', 'Company Name_Kosmotras',
       'Company Name_Lockheed', 'Company Name_General Dynamics',
       'Company Name_Roscosmos', 'Company Name_CASC', 'Company Name_ULA',
       'Company Name_SpaceX', 'Company Name_MHI', 'Company Name_Arianespace',
       'Company Name_ISA', 'Company Name_Northrop', 'Company Name_Boeing',
       'Company Name_US Air Force', 'Company Name_Blue Origin',
       'Company Name_VKS RF', 'Company Name_Sea Launch', 'Company Name_NASA',
       'Company Name_ISAS', 'Company Name_Eurockot',
       'Company Name_Martin Marietta', 'Company Name_ESA', 'Company Name_ILS',
       'Company Name_US Navy', 'Company Name_RVSN USSR',
       'Rocket_type_Grouped_Delta II 7925', 'Rocket_type_Grouped_Other',
       'Rocket_type_Grouped_Tsyklon-2', 'Rocket_type_Grouped_Soyuz U',
       'Rocket_type_Grouped_Molniya-M /Block ML',
       'Rocket_type_Grouped_Vostok-2M',
       'Rocket_type_Grouped_Cosmos-3M (11K65M)',
       'Rocket_type_Grouped_Ariane 5 ECA',
       'Rocket_type_Grouped_Molniya-M /Block 2BL',
       'Rocket_type_Grouped_Tsyklon-3', 'Rocket_type_Grouped_Cosmos-2I (63SM)',
       'Rocket_type_Grouped_Voskhod', 'Country_Other', 'Country_Others',
       'Country_Russia', 'Country_India', 'Country_China', 'Country_France',
       'Country_USA', 'Country_Kazakhstan', 'Country_Japan', 'Extracted_Year',
       'Extracted_Month', 'Status Rocket'],
      dtype='object')

In [ ]:
test_transformed_df.head()

,Company Name_Other,Company Name_ISRO,Company Name_Kosmotras,Company Name_Lockheed,Company Name_General Dynamics,Company Name_Roscosmos,Company Name_CASC,Company Name_ULA,Company Name_SpaceX,Company Name_MHI,...,Country_Russia,Country_India,Country_China,Country_France,Country_USA,Country_Kazakhstan,Country_Japan,Extracted_Year,Extracted_Month,Status Rocket
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.444444,0.545455,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.000000,0.454545,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.158730,0.909091,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.888889,0.909091,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.047619,0.818182,0.0

In [ ]:
test_transformed_df.columns

Index(['Company Name_Other', 'Company Name_ISRO', 'Company Name_Kosmotras',
       'Company Name_Lockheed', 'Company Name_General Dynamics',
       'Company Name_Roscosmos', 'Company Name_CASC', 'Company Name_ULA',
       'Company Name_SpaceX', 'Company Name_MHI', 'Company Name_Arianespace',
       'Company Name_ISA', 'Company Name_Northrop', 'Company Name_Boeing',
       'Company Name_US Air Force', 'Company Name_Blue Origin',
       'Company Name_VKS RF', 'Company Name_Sea Launch', 'Company Name_NASA',
       'Company Name_ISAS', 'Company Name_Eurockot',
       'Company Name_Martin Marietta', 'Company Name_ESA', 'Company Name_ILS',
       'Company Name_US Navy', 'Company Name_RVSN USSR',
       'Rocket_type_Grouped_Delta II 7925', 'Rocket_type_Grouped_Other',
       'Rocket_type_Grouped_Tsyklon-2', 'Rocket_type_Grouped_Soyuz U',
       'Rocket_type_Grouped_Molniya-M /Block ML',
       'Rocket_type_Grouped_Vostok-2M',
       'Rocket_type_Grouped_Cosmos-3M (11K65M)',
       'Rocket_type_Grouped_Ariane 5 ECA',
       'Rocket_type_Grouped_Molniya-M /Block 2BL',
       'Rocket_type_Grouped_Tsyklon-3', 'Rocket_type_Grouped_Cosmos-2I (63SM)',
       'Rocket_type_Grouped_Voskhod', 'Country_Other', 'Country_Others',
       'Country_Russia', 'Country_India', 'Country_China', 'Country_France',
       'Country_USA', 'Country_Kazakhstan', 'Country_Japan', 'Extracted_Year',
       'Extracted_Month', 'Status Rocket'],
      dtype='object')

# Model Building

**1. Train and validation set split with stratification**

In [ ]:
from sklearn.model_selection import train_test_split

X=train_transformed
y=df4_target

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

**2. Trying different baseline models**

1.RandomForest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, confusion_matrix, classification_report
model1 = RandomForestClassifier(random_state=42)
model1.fit(X_train, y_train)
y_pred = model1.predict(X_val)

In [ ]:
f1_score(y_val, y_pred)

0.9454828660436138

In [ ]:
model1.feature_importances_

array([1.28993572e-02, 2.95423003e-03, 6.52309834e-04, 1.24239125e-03,
       6.23262341e-03, 1.66605659e-03, 3.35880580e-03, 2.00720729e-03,
       2.12338475e-03, 1.52024169e-03, 2.44153050e-03, 1.24432557e-02,
       1.95708812e-03, 3.37764361e-03, 6.63213446e-03, 1.27370222e-04,
       3.04836946e-03, 2.22592429e-03, 4.28284830e-03, 1.48893705e-03,
       5.87508636e-04, 3.55235528e-03, 2.41089813e-03, 7.80990526e-04,
       1.00321380e-02, 5.67015650e-03, 3.39352088e-04, 1.10474262e-02,
       1.30682637e-03, 2.14544206e-03, 2.78675821e-03, 2.69525420e-03,
       3.58028990e-03, 6.49436781e-04, 1.26686517e-03, 2.52762802e-03,
       1.96433421e-03, 3.97236349e-03, 0.00000000e+00, 8.52280607e-03,
       5.88466484e-03, 2.34020936e-03, 4.88794941e-03, 2.83533618e-03,
       4.59105526e-03, 9.07278313e-03, 4.00170044e-03, 4.98100494e-01,
       3.11267843e-01, 1.84974245e-02])

2.XGBClassifier

In [ ]:
from xgboost import XGBClassifier
model2 = XGBClassifier(random_state=42, n_estimators=2000,eta=0.01,max_depth=6,gamma=0.001,colsample_bytree=0.5,min_child_weight=5,subsample=1.0)
model2.fit(X_train, y_train)
y_pred = model2.predict(X_val)

In [ ]:
f1_score(y_val, y_pred)

0.9523076923076923

3.LGBMClassifier

In [ ]:
from lightgbm import LGBMClassifier
model3 = LGBMClassifier(random_state=42, n_estimators=100,eta=0.01,max_depth=5,gamma=0.01,colsample_bytree=0.5,sub_sample=0.5)
model3.fit(X_train, y_train)
y_pred = model3.predict(X_val)

[LightGBM] [Warning] Unknown parameter: gamma
[LightGBM] [Warning] Unknown parameter: sub_sample
[LightGBM] [Warning] learning_rate is set=0.1, eta=0.01 will be ignored. Current value: learning_rate=0.1
[LightGBM] [Warning] Unknown parameter: gamma
[LightGBM] [Warning] Unknown parameter: sub_sample
[LightGBM] [Warning] learning_rate is set=0.1, eta=0.01 will be ignored. Current value: learning_rate=0.1
[LightGBM] [Info] Number of positive: 2481, number of negative: 286
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001842 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 158
[LightGBM] [Info] Number of data points in the train set: 2767, number of used features: 43
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.896639 -> initscore=2.160425
[LightGBM] [Info] Start training from score 2.160425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Unknown parameter: gamma
[LightGBM] [Warning] Unknown parameter: sub_sample
[LightGBM] [Warning] learning_rate is set=0.1, eta=0.01 will be ignored. Current value: learning_rate=0.1

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [ ]:
f1_score(y_val, y_pred)

0.9494640122511485

4.Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression

model5 = LogisticRegression()
model5.fit(X_train, y_train)
y_pred = model5.predict(X_val)

In [ ]:
f1_score(y_val, y_pred)

0.9478527607361963

5.SVM

In [ ]:
from sklearn.svm import SVC

model6 = SVC(kernel='linear', random_state=42)
model6.fit(X_train, y_train)
y_pred = model6.predict(X_val)

In [ ]:
f1_score(y_val, y_pred)

0.9479326186830015

**3. Hyperparameter tuning**

1. `SVC` HPT

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
import numpy as np


param_dist = {
    'C': np.logspace(-3, 3, 7),
    'kernel': ['linear'],
    'gamma': ['scale', 'auto']
}

random_search = RandomizedSearchCV(SVC(), param_distributions=param_dist, n_iter=50, cv=3, scoring='f1', random_state=42)


random_search.fit(X_train, y_train)

print(f"Best parameters: {random_search.best_params_}")
print(f"Best score: {random_search.best_score_}")

best_svm = random_search.best_estimator_
y_pred = best_svm.predict(X_val)
print(f1_score(y_val, y_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 14 is smaller than n_iter=50. Running 14 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

KeyboardInterrupt:

In [ ]:
best_svm=SVC(C=0.001, kernel='linear',probability=True)

In [ ]:
best_svm.fit(X_train, y_train)
y_pred = best_svm.predict(X_val)
f1_score(y_val, y_pred)

2. `LogisticRegression` HPT

In [ ]:

model = LogisticRegression(max_iter=1000)

param_grid = {
    'C': np.logspace(-4, 4, 20),
    'penalty': ['l1', 'l2', 'elasticnet', None],
    'solver': ['liblinear', 'saga'],
    'class_weight': [None, 'balanced']
}


search = RandomizedSearchCV(
    model,
    param_distributions=param_grid,
    scoring='f1',
    cv=5,
    n_iter=50,
    random_state=42,
    verbose=1,
    n_jobs=-1
)


search.fit(X_train, y_train)

best_model_log = search.best_estimator_
print("Best Parameters:", search.best_params_)

y_pred = best_model_log.predict(X_val)
f1 = f1_score(y_val, y_pred)
print("Validation F1 Score:", f1)

3. `RandomForestClassifier` HPT

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import StratifiedKFold

model = RandomForestClassifier(random_state=42)


param_dist = {
    'n_estimators': np.arange(50, 200, 50),
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}


random_search = RandomizedSearchCV(estimator=model,
                                   param_distributions=param_dist,
                                   n_iter=100,
                                   cv=3,
                                   verbose=1,
                                   scoring='f1',
                                   random_state=42,
                                   n_jobs=-1)

# Fit the random search to your data (X_train, y_train)
random_search.fit(X_train, y_train)

# Get the best model and parameters
print(f"Best Parameters: {random_search.best_params_}")
best_model = random_search.best_estimator_

# Evaluate the best model
y_pred = best_model.predict(X_val)

In [ ]:
f1_score(y_pred, y_val)

**4. Trying Ensemble Methods**

1. `BaggingClassifier`

In [ ]:
from sklearn.ensemble import BaggingClassifier

ensemble_model = BaggingClassifier(estimator=best_model, random_state=42)
ensemble_model.fit(X_train, y_train)
y_pred = ensemble_model.predict(X_val)

In [ ]:
f1_score(y_val, y_pred)

2. `MLPClassifier`

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:


param_dist = {
    'hidden_layer_sizes': [(50,), (100,), (128, 64), (256,)],
    'activation': ['tanh', 'relu'],
    'solver': ['adam', 'sgd'],
    'learning_rate': ['constant', 'adaptive'],
    'max_iter': [500, 1000, 1500],
    'alpha': np.logspace(-5, 5, 10)
}

mlp = MLPClassifier(random_state=42)

random_search = RandomizedSearchCV(mlp, param_distributions=param_dist, n_iter=10, cv=5, n_jobs=-1,scoring='f1', random_state=42)

random_search.fit(X_train, y_train)


print(f"Best parameters found: {random_search.best_params_}")


best_model_mlp = random_search.best_estimator_
y_pred = best_model_mlp.predict(X_val)


from sklearn.metrics import f1_score
print(f"F1 Score: {f1_score(y_val, y_pred)}")

3.` GradientBoostingClassifier`

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import RandomizedSearchCV

gb = GradientBoostingClassifier(random_state=42)

param_dist = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'min_samples_split': [2, 5, 10]
}

random_search_gb = RandomizedSearchCV(gb, param_distributions=param_dist, n_iter=10, cv=3, scoring='f1', random_state=42)
random_search_gb.fit(X_train ,y_train)

best_gb_model = random_search_gb.best_estimator_
best_gb_model = random_search_gb.best_estimator_
y_pred = best_gb_model.predict(X_val)

from sklearn.metrics import f1_score
print(f"F1 Score: {f1_score(y_val, y_pred)}")

In [ ]:

importances = best_gb_model.feature_importances_

feature_importances_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': importances
})

feature_importances_df = feature_importances_df.sort_values(by='Importance', ascending=False)

print(feature_importances_df)

In [ ]:
threshold = 0.01

important_features = feature_importances_df[feature_importances_df['Importance'] > threshold]['Feature']

X_train_optimized = X_train[important_features]
X_val_optimized = X_val[important_features]

print(f"Important Features: {important_features}")

In [ ]:

best_gb_model.fit(X_train_optimized, y_train)

y_val_pred = best_gb_model.predict(X_val_optimized)

from sklearn.metrics import f1_score
f1 = f1_score(y_val, y_val_pred)
print(f"Optimized F1 Score: {f1}")

In [ ]:

best_gb_model

In [ ]:
train_transformed_df.shape

4. `VotingClassifier`

In [ ]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import f1_score


voting_clf = VotingClassifier(estimators=[
    ('lr', best_model),
    ('rf', best_model_mlp),

    ('svm',best_svm)
], voting='soft')


voting_clf.fit(X_train, y_train)

y_pred = voting_clf.predict(X_val)

f1 = f1_score(y_val, y_pred)
print(f"F1 Score: {f1}")

# Predictions on test set

Submission 1

In [ ]:
y_pred_test = model2.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})

print(final_df.head())

final_df.to_csv('final_predictions.csv', index=False)

Submission 2

In [ ]:
y_pred_test = best_model.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})

print(final_df.head())


final_df.to_csv('final_predictions13.csv', index=False)

In [ ]:
test_transformed_df.shape

Submission 3

In [ ]:
y_pred_test = best_model_mlp.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})

print(final_df.head())

final_df.to_csv('final_predictions14.csv', index=False)

Submission 4

In [ ]:
y_pred_test = model_lgbm.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})

print(final_df.head())

final_df.to_csv('final_predictions`5.csv', index=False)

Submission 5

In [ ]:
y_prob = model.predict_proba(test_transformed_df)[:, 1]
optimal_threshold = 0.4984
y_pred_test = (y_prob >= optimal_threshold).astype(int)
final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})


print(final_df.head())

final_df.to_csv('final_predictions5.csv', index=False)

Miscelleneous trying and testing of models

In [ ]:
y_pred_test = model3.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})


print(final_df.head())

final_df.to_csv('final_predictions3.csv', index=False)

In [ ]:
test_transformed_df.shape

In [ ]:
y_pred_test = best_model.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})

print(final_df.head())


final_df.to_csv('final_predictions15.csv', index=False)

In [ ]:

X_test_optimized = test_transformed_df[important_features]
y_pred_test =best_gb_model.predict(X_test_optimized)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})


print(final_df.head())

final_df.to_csv('final_predictions18.csv', index=False)

ensemble model

In [ ]:
y_pred_test = ensemble_model.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})


print(final_df.head())

final_df.to_csv('final_predictions20.csv', index=False)

In [ ]:
y_pred_test = model2.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})


print(final_df.head())


final_df.to_csv('final_prediction21.csv', index=False)

In [ ]:
y_pred_test = model2.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})

print(final_df.head())

final_df.to_csv('final_prediction22.csv', index=False)

In [ ]:
y_pred_test = model2.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})

print(final_df.head())

final_df.to_csv('final_prediction23.csv', index=False)

In [ ]:
y_pred_test = model2.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,
    'Status Mission': y_pred_test
})

print(final_df.head())

final_df.to_csv('final_prediction26.csv', index=False)

In [ ]:
test_transformed_df.shape

In [ ]:
y_pred_test = model3.predict(test_transformed_df)

final_df = pd.DataFrame({
    'Serial Number': df4_serial_number_test,  # Replace with the actual column name for serial numbers
    'Status Mission': y_pred_test  # The model predictions
})

# Print the final dataframe to verify
print(final_df.head())

# Optionally, you can save this to a CSV file
final_df.to_csv('final_prediction28.csv', index=False)

**Conclusion:-**


1.  Performed in-depth data analysis including feature engineering and EDA.
2.  Tried over 6 basline models.
3.  Enhanced XGBoost and RandomForestClassifier using ensemble techniques.
4.  Conducted feature engineering based on outputs from model.
5.  Acheived an F1 score of 0.95285(XGBoost).

In [ ]:
!pip install --upgrade gradio
!pip install joblib
import gradio as gr
import joblib

Requirement already satisfied: gradio in /usr/local/lib/python3.11/dist-packages (5.23.3)
Requirement already satisfied: aiofiles<24.0,>=22.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (23.2.1)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.9.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.115.12)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.11/dist-packages (from gradio) (0.5.0)
Requirement already satisfied: gradio-client==1.8.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (1.8.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.28.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.30.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.0.2)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.10.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic<2.12,>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.11.1)
Requirement already satisfied: pydub in /usr/local/lib/python3.11/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.0.20)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (6.0.2)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.11.4)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.1.6)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.46.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.13.2)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.15.2)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.13.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.34.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.8.0->gradio) (2025.3.2)
Requirement already satisfied: websockets<16.0,>=10.0 in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.8.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (3.18.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (2.33.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<2.12,>=2.0->gradio) (0.4.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (2.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (1.4.2)

In [ ]:
model = joblib.dump(model2, "model2.pkl")
pipeline= joblib.dump(pipeline,"pipeline.pkl")

In [ ]:
# Load your model and pipeline
model = joblib.load("model2.pkl")
pipeline = joblib.load("pipeline.pkl")  # if you're using a pipeline

In [ ]:
# Load your model and pipeline
model = joblib.load("model2.pkl")
pipeline = joblib.load("pipeline.pkl")  # if you're using a pipeline

# Define options for dropdowns
company_options = ['RVSN USSR', 'CASC', 'VKS RF', 'NASA', 'Arianespace', 'Lockheed',
       'Sea Launch', 'General Dynamics', 'ISRO', 'Kosmotras', 'Boeing',
       'Other', 'Martin Marietta', 'SpaceX', 'ILS', 'MHI', 'Roscosmos',
       'ISA', 'ESA', 'Blue Origin', 'ULA', 'US Air Force', 'Northrop',
       'US Navy', 'ISAS', 'Eurockot']
status_options = [0, 1]
year_options = list(range(1957, 2021))
month_options = list(range(1, 13))
rocket_type_options = ['Voskhod', 'Other', 'Cosmos-2I (63SM)', 'Molniya-M /Block ML',
       'Tsyklon-3', 'Soyuz U', 'Cosmos-3M (11K65M)', 'Tsyklon-2',
       'Vostok-2M', 'Delta II 7925', 'Ariane 5 ECA',
       'Molniya-M /Block 2BL'] # add all types you use
country_options = ['Russia', 'China', 'Kazakhstan', 'USA', 'France', 'Others',
       'India', 'Japan']

def predict(company, status, year, month, rocket_type, country):
    # Create a DataFrame from input
    input_df = pd.DataFrame([{
        'Company Name': company,
        'Status Rocket': status,
        'Extracted_Year': year,
        'Extracted_Month': month,
        'Rocket_type_Grouped': rocket_type,
        'Country': country
    }])

    # Preprocess
    processed_input = pipeline.transform(input_df)  # or call your manual_preprocessing()

    # Predict
    pred = model.predict(processed_input)[0]
    result = "Yes" if pred == 1 else "No"

    return f"🚀 Mission Status Prediction: {result}"

# Create dropdown-based form
demo = gr.Interface(
    fn=predict,
    inputs=[
        gr.Dropdown(company_options, label="Company Name"),
        gr.Dropdown(status_options, label="Status Rocket"),
        gr.Dropdown(year_options, label="Extracted Year"),
        gr.Dropdown(month_options, label="Extracted Month"),
        gr.Dropdown(rocket_type_options, label="Rocket Type Grouped"),
        gr.Dropdown(country_options, label="Country")
    ],
    outputs=gr.Textbox(label="Prediction"),
    title="Space Mission Outcome Predictor",
    description="Fill in the mission details below to predict whether the mission will succeed."
)

demo.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://ef69557d0af01b91d8.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
app_code = '''
import pandas as pd
import gradio as gr
import joblib

# Load your model and pipeline
model = joblib.load("model2.pkl")
pipeline = joblib.load("pipeline.pkl")  # if you're using a pipeline

# Define options for dropdowns
company_options = ['RVSN USSR', 'CASC', 'VKS RF', 'NASA', 'Arianespace', 'Lockheed',
       'Sea Launch', 'General Dynamics', 'ISRO', 'Kosmotras', 'Boeing',
       'Other', 'Martin Marietta', 'SpaceX', 'ILS', 'MHI', 'Roscosmos',
       'ISA', 'ESA', 'Blue Origin', 'ULA', 'US Air Force', 'Northrop',
       'US Navy', 'ISAS', 'Eurockot']
status_options = [0, 1]
year_options = list(range(1957, 2021))
month_options = list(range(1, 13))
rocket_type_options = ['Voskhod', 'Other', 'Cosmos-2I (63SM)', 'Molniya-M /Block ML',
       'Tsyklon-3', 'Soyuz U', 'Cosmos-3M (11K65M)', 'Tsyklon-2',
       'Vostok-2M', 'Delta II 7925', 'Ariane 5 ECA',
       'Molniya-M /Block 2BL'] # add all types you use
country_options = ['Russia', 'China', 'Kazakhstan', 'USA', 'France', 'Others',
       'India', 'Japan']

def predict(company, status, year, month, rocket_type, country):
    # Create a DataFrame from input
    input_df = pd.DataFrame([{
        'Company Name': company,
        'Status Rocket': status,
        'Extracted_Year': year,
        'Extracted_Month': month,
        'Rocket_type_Grouped': rocket_type,
        'Country': country
    }])

    # Preprocess
    processed_input = pipeline.transform(input_df)

    # Predict
    pred = model.predict(processed_input)[0]
    result = "Yes" if pred == 1 else "No"

    return f"🚀 Mission Status Prediction: {result}"

# Create dropdown-based form
demo = gr.Interface(
    fn=predict,
    inputs=[
        gr.Dropdown(company_options, label="Company Name"),
        gr.Dropdown(status_options, label="Status Rocket"),
        gr.Dropdown(year_options, label="Extracted Year"),
        gr.Dropdown(month_options, label="Extracted Month"),
        gr.Dropdown(rocket_type_options, label="Rocket Type Grouped"),
        gr.Dropdown(country_options, label="Country")
    ],
    outputs=gr.Textbox(label="Prediction"),
    title="Space Mission Outcome Predictor",
    description="Fill in the mission details below to predict whether the mission will succeed."
)

demo.launch(share=True)
'''

# Write to app.py
with open("app.py", "w") as f:
    f.write(app_code)

In [ ]:
!python app.py

* Running on local URL:  http://127.0.0.1:7861
* Running on public URL: https://5bc38881aabb6b1fbe.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
Created dataset file at: .gradio/flagged/dataset1.csv
Keyboard interruption in main thread... closing server.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gradio/blocks.py", line 2997, in block_thread
    time.sleep(0.1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/app.py", line 62, in <module>
    demo.launch(share=True)
  File "/usr/local/lib/python3.11/dist-packages/gradio/blocks.py", line 2903, in launch
    self.block_thread()
  File "/usr/local/lib/python3.11/dist-packages/gradio/blocks.py", line 3001, in block_thread
    self.server.close()
  File "/usr/local/lib/python3.11/dist-packages/gradio/http_server.py", line 69, in close
    self.thread.join(timeout=5)
  File "/usr/lib/python3.11/threading.py", line 1123, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/usr/lib/python3.11/threading.py", line 1139, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Killing tunnel 127.0.0.1:7861 <> https://5bc38881aabb6b1fbe.gradio.live
^C



---



---